version: '3'
services: 
    my_mongo_service:
        container_name: 'my_mongo_service'
        image: 'krytlewski/my_mongo:latest'
        ports: 
            - 27017:27017
    
    my_backend_service:
        container_name: 'my_backend_service'
        image: 'krytlewski/my_backend:latest'
        ports: 
            - 8090:8090
